// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $author_guidelines from "./routes/author-guidelines.tsx";
import * as $call_for_contributions from "./routes/call-for-contributions.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $organizers from "./routes/organizers.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $History from "./islands/History.tsx";
import * as $Navigation from "./islands/Navigation.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/author-guidelines.tsx": $author_guidelines,
    "./routes/call-for-contributions.tsx": $call_for_contributions,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/organizers.tsx": $organizers,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/History.tsx": $History,
    "./islands/Navigation.tsx": $Navigation,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
