// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_ from "./routes/[slug].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_nav from "./routes/api/nav.tsx";
import * as $api_submission_dates from "./routes/api/submission-dates.tsx";
import * as $api_test from "./routes/api/test.tsx";
import * as $call_for_contributions from "./routes/call-for-contributions.tsx";
import * as $call_for_contributions_critiques from "./routes/call-for-contributions/critiques.tsx";
import * as $call_for_contributions_demos from "./routes/call-for-contributions/demos.tsx";
import * as $call_for_contributions_doctoral_consortium from "./routes/call-for-contributions/doctoral-consortium.tsx";
import * as $call_for_contributions_papers from "./routes/call-for-contributions/papers.tsx";
import * as $call_for_contributions_work_in_progress from "./routes/call-for-contributions/work-in-progress.tsx";
import * as $call_for_contributions_workshops from "./routes/call-for-contributions/workshops.tsx";
import * as $index from "./routes/index.tsx";
import * as $organisers from "./routes/organisers.tsx";
import * as $past_conferences from "./routes/past-conferences.tsx";
import * as $programme from "./routes/programme.tsx";
import * as $ConferenceTimeline from "./islands/ConferenceTimeline.tsx";
import * as $ExpandableBio from "./islands/ExpandableBio.tsx";
import * as $History from "./islands/History.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $NavDropdown from "./islands/NavDropdown.tsx";
import * as $XBreaker from "./islands/XBreaker.tsx";
import * as $importantDates from "./islands/importantDates.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $_slug_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/nav.tsx": $api_nav,
    "./routes/api/submission-dates.tsx": $api_submission_dates,
    "./routes/api/test.tsx": $api_test,
    "./routes/call-for-contributions.tsx": $call_for_contributions,
    "./routes/call-for-contributions/critiques.tsx":
      $call_for_contributions_critiques,
    "./routes/call-for-contributions/demos.tsx": $call_for_contributions_demos,
    "./routes/call-for-contributions/doctoral-consortium.tsx":
      $call_for_contributions_doctoral_consortium,
    "./routes/call-for-contributions/papers.tsx":
      $call_for_contributions_papers,
    "./routes/call-for-contributions/work-in-progress.tsx":
      $call_for_contributions_work_in_progress,
    "./routes/call-for-contributions/workshops.tsx":
      $call_for_contributions_workshops,
    "./routes/index.tsx": $index,
    "./routes/organisers.tsx": $organisers,
    "./routes/past-conferences.tsx": $past_conferences,
    "./routes/programme.tsx": $programme,
  },
  islands: {
    "./islands/ConferenceTimeline.tsx": $ConferenceTimeline,
    "./islands/ExpandableBio.tsx": $ExpandableBio,
    "./islands/History.tsx": $History,
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/NavDropdown.tsx": $NavDropdown,
    "./islands/XBreaker.tsx": $XBreaker,
    "./islands/importantDates.tsx": $importantDates,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
