name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build static site
        run: |
          deno task build
          echo "Build completed. Listing _fresh directory:"
          ls -la _fresh

      - name: Create index.html
        run: |
          cat > _fresh/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Aarhus 2025 Conference</title>
            <link rel="stylesheet" href="/aarhus2025-static/static/styles.css">
          </head>
          <body>
            <div id="root"></div>
            <script type="module" src="/aarhus2025-static/main.js"></script>
          </body>
          </html>
          EOL

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: magniswerfer/aarhus2025-static
          token: ${{ secrets.DEPLOY_PAT }}
          path: gh-pages

      - name: Copy built files
        run: |
          rm -rf gh-pages/*
          # Copy Fresh build files
          cp -r _fresh/* gh-pages/
          # Create static directory and copy static files
          mkdir -p gh-pages/static
          cp -r static/* gh-pages/static/
          echo "Files in gh-pages directory:"
          ls -la gh-pages
          echo "Files in gh-pages/static directory:"
          ls -la gh-pages/static

      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy site update"
          git push
