name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build static site
        run: deno task build

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: magniswerfer/aarhus2025-static
          token: ${{ secrets.DEPLOY_PAT }}
          path: gh-pages

      - name: Copy built files
        run: |
          rm -rf gh-pages/*
          cp -r _fresh/* gh-pages/
          cp -r static/* gh-pages/  # Copy static assets if they exist

      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy site update"
          git push

